/// Flutter icons CustomIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
///
// ignore_for_file: constant_identifier_names

import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData verified_shield = IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData information = IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData languaje = IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cross_ways = IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData viva_city = IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData coin = IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gear = IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData document = IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData share = IconData(0xe80b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData calendar = IconData(0xe80c, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
